### PR TITLE
Updated GameScene and mouse click detection. Maps are now centered and

### PR DESCRIPTION
**Pull request by mloho**
the main view follows the player!!

Signed-off-by: Melvin Loho mloho@outlook.com

### CODE REVIEW

**Comment by rhealauzon** [comment]
Your request is empty but ill merge it in case git is being weird..? Double check it please.

**Comment by mloho** [comment]
NOOO

**Comment by mloho** [comment]
I wasn't done updating it....

**Comment by mloho** [comment]
I was a minute away from pushing the commit that actually mattered.

**Comment by rhealauzon** [comment]
Im sorry! D:

**Pull request merged**
